services:

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"  # Load from .env
      POSTGRES_USER: "${POSTGRES_USER}"  # Load from .env
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"  # Load from .env
      # PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - hack-db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"  # Use the port from .env
    command: ["postgres", "-p", "${POSTGRES_PORT}"]  # Explicitly set the port

  bot:
    build: ./
    container_name: aiogram_bot
    environment:
      - DATABASE_URL=postgresql://hackuser:hackpassword@postgres:5433/hackdb
    volumes:
      - "${HOME}/data:/app/media"  # Updated volume mount
    depends_on:
      - postgres
    tty: true
    stdin_open: true
volumes:
  hack-db:
